# Generated by Django 5.0.4 on 2024-04-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='feels_like',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_max',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_min',
            field=models.FloatField(default=False),
        ),
    ]
